apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: sanofi-webol-hpa
 namespace: tradetools-webol
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: php-sanofi-deployment
 minReplicas: 6
 maxReplicas: 20
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 60
 - type: Resource
   resource:
    name: memory
    target:
      type: Utilization
      averageUtilization: 85