apiVersion: v1
kind: PersistentVolume
metadata:
  name: webb-sanofi
  namespace: tradetools-webol
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /files
    server: 10.222.227.74